### ISSUE TITLE
在10000并发的时候，出现以下错误

### ISSUE THREAD

**Issue by fisnone** [didi/GateKeeper#3]
[ERROR][2019-12-27T09:14:49.186][log.go:74] _undef||func=module_proxy_errorhandler||err=dial tcp 192.168.212.87:8198: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.||url=http://192.168.212.87:8198/ping||traceid=c0a8d4575e055b0913f83df8262c01b0||cspanid=||spanid=9ead8f5e53780187
能看下这问题

**Comment by e421083458** [comment]
dial tcp 192.168.212.87:8198: connect，说明你的下游服务连接被打满了导致服务不可用。感觉应该是你的下游服务并发量有问题。
你可以压测一下单台下游服务的并发量 或者 增加一个下游服务节点再压测一下网关试试。

**Comment by fisnone** [comment]
查了一下，应该是transport连接池的问题，把目标下游服务节点的tcp连接占满了，通过修改下游服务节点的最大连接数可以解决这个，但是我搭建的其他gateway就不存在这个问题

**Comment by e421083458** [comment]
连接池被打满问题已经修复，你可以再试一下。
